data link
https://www.datos.gob.mx/dataset/datos_viales

In [ ]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

df = pd.read_csv("data/Datos_viales_2013_2024.csv")
municipios = gpd.read_file("data/Mexico_mun_layer_simplified.shp")  # INEGI shapefile

# Create GeoDataFrame from your data
gdf = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(df.longitud, df.latitud),
    crs="EPSG:4326"
)

# Reproject to match shapefile CRS if needed
municipios = municipios.to_crs("EPSG:4326")

# Spatial join
result = gpd.sjoin(gdf, municipios[["NOMGEO", "geometry"]], how="left", predicate="within")
result = result.rename(columns={"NOMGEO": "municipio"})
result.drop(columns=["geometry", "index_right"])

/opt/anaconda3/envs/torch/lib/python3.12/site-packages/pyogrio/raw.py:200: RuntimeWarning: data/Mexico_mun_layer_simplified.shp contains polygon(s) with rings with invalid winding order. Autocorrecting them, but that shapefile should be corrected using ogr2ogr for example.
  return ogr_read(

In [2]:
result.head()

,estado,carretera,clave,ruta,punto_generador,km,te,sc,tdpa,m,...,bb,cc,k,d,latitud,longitud,ejercicio,geometry,index_right,municipio
0,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,1.0,6827.0,6.1,...,0.6,3.3,0.071,0.520,22.146662,-102.290244,2024,POINT (-102.29024 22.14666),5.0,Pabellón de Arteaga
1,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,1.0,811.0,3.5,...,4.5,9.2,0.074,0.518,22.146570,-102.290230,2024,POINT (-102.29023 22.14657),5.0,Pabellón de Arteaga
2,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,2.0,7399.0,6.1,...,0.6,3.5,0.069,0.520,22.146735,-102.290236,2024,POINT (-102.29024 22.14674),5.0,Pabellón de Arteaga
3,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,2.0,753.0,4.2,...,4.3,9.9,0.097,0.518,22.146823,-102.290227,2024,POINT (-102.29023 22.14682),5.0,Pabellón de Arteaga
4,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,Pabellon_de_Arteaga,1.8,1.0,1.0,6377.0,2.8,...,0.8,5.9,0.074,0.537,22.147018,-102.285324,2024,POINT (-102.28532 22.14702),5.0,Pabellón de Arteaga

In [7]:
print(result.isna().sum())
print(len(result))

estado                 0
carretera              0
clave                  0
ruta                   0
punto_generador        0
km                     0
te                 17110
sc                 17112
tdpa                   0
m                  17150
a                  17150
b                  17150
c2                 17150
c3                 17150
t3s2               17150
t3s3               17150
t3s2r4             17150
otros              17150
aa                 17150
bb                 17150
cc                 17150
k                  17150
d                  17140
latitud            17160
longitud           17173
ejercicio              0
geometry               0
index_right        27992
municipio          27992
dtype: int64
147108

In [ ]:
# Are the missing-municipio rows random, or clustered?
print(result[result["municipio"].isna()]["estado"].value_counts())
print(result[result["municipio"].isna()]["ejercicio"].value_counts())

estado
Mexico                 2452
Veracruz               1610
Puebla                 1582
Jalisco                1279
Michoacan              1091
Hidalgo                1080
Guanajuato             1065
Morelos                 994
Zacatecas               963
Tlaxcala                961
San Luis Potosi         950
Coahuila                907
Chiapas                 889
Guerrero                871
Tamaulipas              859
Nuevo Leon              857
Oaxaca                  847
Tabasco                 776
Aguascalientes          742
Ciudad de Mexico        736
Yucatan                 657
Queretaro               649
Colima                  627
Chihuahua               601
Sinaloa                 579
Quintana Roo            539
Nayarit                 521
Baja California         499
Sonora                  494
Campeche                472
Baja California Sur     472
Durango                 371
Name: count, dtype: int64
ejercicio
2015    11295
2022     1692
2023     1684
2021     1682
2020     1669
2019     1523
2018     1511
2016     1468
2017     1442
2013     1398
2014     1387
2024     1241
Name: count, dtype: int64

In [ ]:
## missing municipio rows are well balanced so we drop NA rows
result = result.dropna()

In [10]:
print(result.isna().sum())
print(len(result))

estado             0
carretera          0
clave              0
ruta               0
punto_generador    0
km                 0
te                 0
sc                 0
tdpa               0
m                  0
a                  0
b                  0
c2                 0
c3                 0
t3s2               0
t3s3               0
t3s2r4             0
otros              0
aa                 0
bb                 0
cc                 0
k                  0
d                  0
latitud            0
longitud           0
ejercicio          0
geometry           0
index_right        0
municipio          0
dtype: int64
119111

In [11]:
result.head()

,estado,carretera,clave,ruta,punto_generador,km,te,sc,tdpa,m,...,bb,cc,k,d,latitud,longitud,ejercicio,geometry,index_right,municipio
0,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,1.0,6827.0,6.1,...,0.6,3.3,0.071,0.520,22.146662,-102.290244,2024,POINT (-102.29024 22.14666),5.0,Pabellón de Arteaga
1,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,1.0,811.0,3.5,...,4.5,9.2,0.074,0.518,22.146570,-102.290230,2024,POINT (-102.29023 22.14657),5.0,Pabellón de Arteaga
2,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Alta,0.0,3.0,2.0,7399.0,6.1,...,0.6,3.5,0.069,0.520,22.146735,-102.290236,2024,POINT (-102.29024 22.14674),5.0,Pabellón de Arteaga
3,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,T_C_Aguascalientes-Zacatecas_Baja,0.0,3.0,2.0,753.0,4.2,...,4.3,9.9,0.097,0.518,22.146823,-102.290227,2024,POINT (-102.29023 22.14682),5.0,Pabellón de Arteaga
4,Aguascalientes,Acceso_a_Pabellon_de_Arteaga,1113.0,MEX-045,Pabellon_de_Arteaga,1.8,1.0,1.0,6377.0,2.8,...,0.8,5.9,0.074,0.537,22.147018,-102.285324,2024,POINT (-102.28532 22.14702),5.0,Pabellón de Arteaga

In [12]:
result['municipio'].nunique()

1255

covariates to use 
- tdpa: average daily traffic (collapse into mean for each municipality)
- punto_generador: traffic generation point (count of unique stations)
vehicles: (percentage share of traffic composition?)
- m: motorcycles
- a: automobiles
- b: buses
- c2: 2 axle truck
- c3: 3 acle truck
- t3s2: tractor trailer (3 axle tractor, 2 axle semi)
- t3s3: tractor trailer (3 axle, 3 axle semi)
- t3s2r4: tractor trailer with dolly (3, 2, 4 axles)
- aa: automobiles adjusted
- bb: buses adjusted
- cc: trucks adjusted

In [ ]:
# checking for punto_generador counts per municipio using Calvillo just to check 
result[result['municipio'] == "Calvillo" ]

,estado,carretera,clave,ruta,punto_generador,km,te,sc,tdpa,m,...,bb,cc,k,d,latitud,longitud,ejercicio,geometry,index_right,municipio
19,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,T_Izq_Malpaso,45.1,1.0,0.0,8622.0,3.0,...,1.3,4.5,0.109,0.524,21.880885,-102.653291,2024,POINT (-102.65329 21.88088),6.0,Calvillo
20,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Presa_La_Codorniz,49.3,3.0,1.0,10569.0,4.3,...,1.7,4.8,0.088,0.523,21.863653,-102.692502,2024,POINT (-102.6925 21.86365),6.0,Calvillo
21,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Presa_La_Codorniz,49.3,3.0,2.0,11570.0,5.4,...,1.6,5.5,0.088,0.523,21.863601,-102.692345,2024,POINT (-102.69234 21.8636),6.0,Calvillo
22,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,Calvillo,52.3,3.0,1.0,5386.0,3.0,...,1.0,4.7,0.096,0.501,21.834250,-102.748144,2024,POINT (-102.74814 21.83425),6.0,Calvillo
23,Aguascalientes,Aguascalientes-Jalpa,95.0,MEX-070,Calvillo,52.3,3.0,2.0,5354.0,2.9,...,0.7,4.5,0.087,0.501,21.834117,-102.748073,2024,POINT (-102.74807 21.83412),6.0,Calvillo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146062,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Presa_La_Codorniz,49.3,3.0,1.0,8407.0,1.0,...,1.2,6.9,0.100,0.500,21.864000,-102.692000,2013,POINT (-102.692 21.864),6.0,Calvillo
146063,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Presa_La_Codorniz,49.3,3.0,2.0,8824.0,0.9,...,1.4,7.8,0.100,0.500,21.864000,-102.692000,2013,POINT (-102.692 21.864),6.0,Calvillo
146064,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,Calvillo,52.3,3.0,1.0,4636.0,1.4,...,1.7,8.4,0.100,0.500,21.839000,-102.740000,2013,POINT (-102.74 21.839),6.0,Calvillo
146065,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,Calvillo,52.3,3.0,2.0,4706.0,1.2,...,1.8,9.3,0.100,0.500,21.839000,-102.740000,2013,POINT (-102.74 21.839),6.0,Calvillo
146066,Zacatecas,Aguascalientes-Jalpa,95.0,MEX-070,T_Der_Jaltiche_de_Abajo,63.8,3.0,0.0,5001.0,0.6,...,2.2,10.5,0.100,0.500,21.771000,-102.804000,2013,POINT (-102.804 21.771),6.0,Calvillo

In [14]:
result[["m","a","b","c2","c3","t3s2","t3s3","t3s2r4","otros"]].sum(axis=1).describe()

count    119111.000000
mean        100.001342
std           0.176938
min          99.600000
25%         100.000000
50%         100.000000
75%         100.000000
max         132.700000
dtype: float64

In [15]:
result.to_csv("roads1.csv", index=False)