In [23]:
import pandas as pd

df = pd.read_csv("data/ethan_final_key_df_head.csv")
roads = pd.read_csv("roads1.csv")
ice = pd.read_csv("data/ice_covariates.csv")
census = pd.read_csv("data/mexico_census_infrastructure_data.csv")
schools = pd.read_csv("data/school_infrastructure_covariates.csv")

In [24]:
df.head()

,CVEGEO,NOMGEO,homicidio_doloso_2025,robo_veh_violencia_2025,n_inseguro_popw
0,1005,Jesús María,15.0,16.0,48465.88493
1,1008,San José de Gracia,1.0,1.0,NaN
2,1001,Aguascalientes,41.0,47.0,264703.23100
3,1004,Cosío,2.0,7.0,NaN
4,1011,San Francisco de los Romo,5.0,5.0,18028.05971

In [25]:
roads.head()

,municipio,CVEGEO,tdpa_mean,no_tdpa_mean,punto_generador_count,no_punto_generador_count,m_mean,no_m_mean,a_mean,no_a_mean,...,t3s2r4_mean,no_t3s2r4_mean,otros_mean,no_otros_mean,aa_mean,no_aa_mean,bb_mean,no_bb_mean,cc_mean,no_cc_mean
0,Aguascalientes,1001,11298.763489,0,30.0,0,2.917626,0,80.986960,0,...,1.057104,0,0.368615,0,83.904586,0,2.227788,0,13.867626,0
1,Asientos,1002,4616.674641,0,10.0,0,5.194737,0,80.874641,0,...,0.126794,0,0.233014,0,86.069378,0,1.878469,0,12.052153,0
2,Calvillo,1003,4997.627660,0,11.0,0,2.532979,0,88.263298,0,...,0.090957,0,0.110106,0,90.796277,0,0.742553,0,8.461170,0
3,Cosío,1004,6973.539568,0,3.0,0,3.200719,0,68.954676,0,...,3.424460,0,0.668345,0,72.155396,0,4.274101,0,23.570504,0
4,Jesús María,1005,11065.404598,0,16.0,0,2.894713,0,83.057011,0,...,0.579310,0,0.248046,0,85.951724,0,1.494253,0,12.554023,0

In [26]:
roads = roads.drop(columns=['municipio'])

In [27]:
ice.head()

,CVEGEO,NOMGEO,IM_2020,no_IM_2020,IE,no_IE,TCVCU,no_TCVCU,ICE,no_ICE
0,1005,Jesús María,59.011762,0,2.757816,0,10,0,15.172939,0
1,1008,San José de Gracia,57.527531,0,0.624208,0,30,0,12.413795,0
2,1001,Aguascalientes,60.318795,0,30.802086,0,2,0,43.710758,0
3,1004,Cosío,57.114030,0,0.318518,0,25,0,12.080517,0
4,1011,San Francisco de los Romo,58.552098,0,0.966893,0,13,0,13.220455,0

In [28]:
ice = ice.drop(columns = ['NOMGEO'])

In [29]:
census.head()

,CVEGEO,NOMGEO,VIVPAR_HAB,no_VIVPAR_HAB,POBTOT,no_POBTOT,pct_VPH_SINTIC,no_pct_VPH_SINTIC,pct_VPH_C_ELEC,no_pct_VPH_C_ELEC,pct_VPH_AGUADV,no_pct_VPH_AGUADV,pct_VPH_PISODT,no_pct_VPH_PISODT,pct_VPH_PISOTI,no_pct_VPH_PISOTI,pct_VPH_1CUART,no_pct_VPH_1CUART
0,1005,Jesús María,32267,0,129929,0,0.004587,0,1.022004,0,1.017913,0,1.014008,0,0.012737,0,0.024576,0
1,1008,San José de Gracia,2377,0,9552,0,0.015145,0,0.986538,0,0.981489,0,0.990324,0,0.010097,0,0.028187,0
2,1001,Aguascalientes,257719,0,948990,0,0.002836,0,1.031298,0,1.029152,0,1.026940,0,0.005937,0,0.012358,0
3,1004,Cosío,3933,0,17000,0,0.012713,0,0.993135,0,0.991609,0,0.989321,0,0.010170,0,0.030511,0
4,1011,San Francisco de los Romo,16194,0,61997,0,0.005866,0,1.004137,0,1.003335,0,1.001482,0,0.007225,0,0.015314,0

In [30]:
census = census.drop(columns = ['NOMGEO'])

In [31]:
schools.head()

,CVEGEO,NOMGEO,n_schools_avg,no_n_schools_avg,pct_con_bebederos,no_pct_con_bebederos,pct_con_proteccion_civil,no_pct_con_proteccion_civil,pct_con_cancha,no_pct_con_cancha,avg_anio_creacion,no_avg_anio_creacion
0,1005,JESUS MARIA,10.666667,0,0.180995,0,0.161388,0,0.567873,0,1980.245852,0
1,1008,SAN JOSE DE GRACIA,6.000000,0,0.500000,0,0.666667,0,0.333333,0,1987.333333,0
2,1001,AGUASCALIENTES,25.333333,0,0.559261,0,0.473644,0,0.717439,0,1978.161775,0
3,1004,COSIO,5.500000,0,0.732143,0,0.196429,0,0.714286,0,1968.678571,0
4,1011,SAN FRANCISCO DE LOS ROMO,6.000000,0,0.312500,0,0.125000,0,0.687500,0,1983.687500,0

In [32]:
schools = schools.drop(columns = ['NOMGEO'])

In [33]:
print(df["CVEGEO"].nunique())
print(roads["CVEGEO"].nunique())
print(ice["CVEGEO"].nunique())
print(census["CVEGEO"].nunique())
print(schools["CVEGEO"].nunique())

2478
2486
2478
2478
2478

In [34]:
anti_join1 = df[~df["CVEGEO"].isin(roads["CVEGEO"])]

print(anti_join1["CVEGEO"].nunique())

anti_join2 = roads[~roads["CVEGEO"].isin(df["CVEGEO"])]

print(anti_join2["CVEGEO"].nunique())
print(anti_join2["CVEGEO"].unique())

print(anti_join2)

0
8
[ 9998 14998 20999 22998 26998 26999 30998 30999]
      CVEGEO  tdpa_mean  no_tdpa_mean  punto_generador_count  \
291     9998        0.0             1                    0.0
671    14998        0.0             1                    0.0
1587   20999        0.0             1                    0.0
1823   22998        0.0             1                    0.0
1986   26998        0.0             1                    0.0
1987   26999        0.0             1                    0.0
2320   30998        0.0             1                    0.0
2321   30999        0.0             1                    0.0

      no_punto_generador_count  m_mean  no_m_mean  a_mean  no_a_mean  b_mean  \
291                          1     0.0          1     0.0          1     0.0
671                          1     0.0          1     0.0          1     0.0
1587                         1     0.0          1     0.0          1     0.0
1823                         1     0.0          1     0.0          1     0.0
1986                         1     0.0          1     0.0          1     0.0
1987                         1     0.0          1     0.0          1     0.0
2320                         1     0.0          1     0.0          1     0.0
2321                         1     0.0          1     0.0          1     0.0

      ...  t3s2r4_mean  no_t3s2r4_mean  otros_mean  no_otros_mean  aa_mean  \
291   ...          0.0               1         0.0              1      0.0
671   ...          0.0               1         0.0              1      0.0
1587  ...          0.0               1         0.0              1      0.0
1823  ...          0.0               1         0.0              1      0.0
1986  ...          0.0               1         0.0              1      0.0
1987  ...          0.0               1         0.0              1      0.0
2320  ...          0.0               1         0.0              1      0.0
2321  ...          0.0               1         0.0              1      0.0

      no_aa_mean  bb_mean  no_bb_mean  cc_mean  no_cc_mean
291            1      0.0           1      0.0           1
671            1      0.0           1      0.0           1
1587           1      0.0           1      0.0           1
1823           1      0.0           1      0.0           1
1986           1      0.0           1      0.0           1
1987           1      0.0           1      0.0           1
2320           1      0.0           1      0.0           1
2321           1      0.0           1      0.0           1

[8 rows x 29 columns]

In [35]:
codes_to_drop = [9998, 14998, 20999, 22998, 26998, 26999, 30998, 30999]
roads = roads[~roads["CVEGEO"].isin(codes_to_drop)]

In [36]:
print(df["CVEGEO"].nunique())
print(roads["CVEGEO"].nunique())
print(ice["CVEGEO"].nunique())
print(census["CVEGEO"].nunique())
print(schools["CVEGEO"].nunique())

2478
2478
2478
2478
2478

In [37]:
merged = df.merge(roads, on="CVEGEO", how="outer") \
           .merge(ice, on="CVEGEO", how="outer") \
           .merge(census, on="CVEGEO", how="outer") \
           .merge(schools, on="CVEGEO", how="outer")

In [39]:
merged.head()

,CVEGEO,NOMGEO,homicidio_doloso_2025,robo_veh_violencia_2025,n_inseguro_popw,tdpa_mean,no_tdpa_mean,punto_generador_count,no_punto_generador_count,m_mean,...,n_schools_avg,no_n_schools_avg,pct_con_bebederos,no_pct_con_bebederos,pct_con_proteccion_civil,no_pct_con_proteccion_civil,pct_con_cancha,no_pct_con_cancha,avg_anio_creacion,no_avg_anio_creacion
0,1001,Aguascalientes,41.0,47.0,264703.23100,11298.763489,0,30.0,0,2.917626,...,25.333333,0,0.559261,0,0.473644,0,0.717439,0,1978.161775,0
1,1002,Asientos,3.0,10.0,20111.86968,4616.674641,0,10.0,0,5.194737,...,14.333333,0,0.219096,0,0.325661,0,0.510941,0,1975.178460,0
2,1003,Calvillo,0.0,2.0,14514.80605,4997.627660,0,11.0,0,2.532979,...,14.000000,0,0.164141,0,0.194444,0,0.618687,0,1986.751263,0
3,1004,Cosío,2.0,7.0,NaN,6973.539568,0,3.0,0,3.200719,...,5.500000,0,0.732143,0,0.196429,0,0.714286,0,1968.678571,0
4,1005,Jesús María,15.0,16.0,48465.88493,11065.404598,0,16.0,0,2.894713,...,10.666667,0,0.180995,0,0.161388,0,0.567873,0,1980.245852,0

In [ ]:
merged.columns.tolist()

['CVEGEO',
 'NOMGEO',
 'homicidio_doloso_2025',
 'robo_veh_violencia_2025',
 'n_inseguro_popw',
 'tdpa_mean',
 'no_tdpa_mean',
 'punto_generador_count',
 'no_punto_generador_count',
 'm_mean',
 'no_m_mean',
 'a_mean',
 'no_a_mean',
 'b_mean',
 'no_b_mean',
 'c2_mean',
 'no_c2_mean',
 'c3_mean',
 'no_c3_mean',
 't3s2_mean',
 'no_t3s2_mean',
 't3s3_mean',
 'no_t3s3_mean',
 't3s2r4_mean',
 'no_t3s2r4_mean',
 'otros_mean',
 'no_otros_mean',
 'aa_mean',
 'no_aa_mean',
 'bb_mean',
 'no_bb_mean',
 'cc_mean',
 'no_cc_mean',
 'IM_2020',
 'no_IM_2020',
 'IE',
 'no_IE',
 'TCVCU',
 'no_TCVCU',
 'ICE',
 'no_ICE',
 'VIVPAR_HAB',
 'no_VIVPAR_HAB',
 'POBTOT',
 'no_POBTOT',
 'pct_VPH_SINTIC',
 'no_pct_VPH_SINTIC',
 'pct_VPH_C_ELEC',
 'no_pct_VPH_C_ELEC',
 'pct_VPH_AGUADV',
 'no_pct_VPH_AGUADV',
 'pct_VPH_PISODT',
 'no_pct_VPH_PISODT',
 'pct_VPH_PISOTI',
 'no_pct_VPH_PISOTI',
 'pct_VPH_1CUART',
 'no_pct_VPH_1CUART',
 'n_schools_avg',
 'no_n_schools_avg',
 'pct_con_bebederos',
 'no_pct_con_bebederos',
 'pct_con_proteccion_civil',
 'no_pct_con_proteccion_civil',
 'pct_con_cancha',
 'no_pct_con_cancha',
 'avg_anio_creacion',
 'no_avg_anio_creacion']

In [41]:
merged.to_csv("merged_covariates.csv")